name: sit-chatbot
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.12
  - pip
  - numpy
  - faiss-gpu
  - sentence-transformers
  - tqdm
  - requests
  - pip:
      - llama-cpp-python
      - torch
      - torchvision
      - torchaudio
      - --extra-index-url https://download.pytorch.org/whl/cu121